#!/bin/sh

#echo "Validating current branch..."

#protected_branch='master'
#current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

#if [ $protected_branch = $current_branch ]
#  then
#    echo "You can not push to master!"
#    exit 1
#fi

echo "Validating Kotlin code with detekt..."

./gradlew detekt --stacktrace --no-daemon

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no issues. Proceeding with push."
    exit 0
else
    echo 1>&2 "Static analysis found issues you need to fix before pushing."
    exit 1
fi
